#
# NOTE: This docker-compose is not used for building the rapidpro docker
#       releases, it is a compose file for local development purposes.
#

version: '2'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - rapidpro
      - courier
    links:
      - rapidpro
      - courier
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  rapidpro:
    image: oguya/rapidpro-docker:v5.5.0
    volumes:
      - ./settings.py:/rapidpro/temba/settings.py
    depends_on:
      - redis
      - postgresql
      - courier
      - mailroom
      - elasticsearch
    expose:
      - '8000'
    environment:
      - DOMAIN_NAME=localhost
      - ALLOWED_HOSTS=localhost
      - TEMBA_HOST=localhost
      - DJANGO_DEBUG=off
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=on
      - MANAGEPY_MIGRATE=on
      - MAILROOM_URL=http://mailroom:8090
      - MAILROOM_AUTH_TOKEN=Gqcqvi2PGkoZMpQi
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  celery:
    image: oguya/rapidpro-docker:v5.5.0
    depends_on:
      - rapidpro
      - mailroom
      - elasticsearch
    links:
      - redis
      - postgresql
      - mailroom
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
      - MAILROOM_URL=http://mailroom:8090
      - MAILROOM_AUTH_TOKEN=Gqcqvi2PGkoZMpQi
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    command: ["/venv/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery"]

  redis:
    image: redis:alpine

  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=rapidpro
    volumes:
    - .postgres_data/:/var/lib/postgres/

  courier:
    image: praekeltfoundation/courier:latest
    depends_on:
      - postgresql
      - redis
    expose:
      - '8080'
    links:
      - redis
      - postgresql
    environment:
      - COURIER_DB=postgres://postgres:postgres@postgresql/rapidpro
      - COURIER_REDIS=redis://redis:6379/0
      - COURIER_DOMAIN=localhost
      - COURIER_SPOOL_DIR=/home/courier/spool/persisted/

  indexer:
    image: praekeltfoundation/rp-indexer:latest
    depends_on:
      - postgresql
      - elasticsearch
    links:
      - postgresql
      - elasticsearch
    environment:
      - INDEXER_DB=postgresql://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - INDEXER_ELASTIC_URL=http://elasticsearch:9200

  elasticsearch:
    image: elasticsearch:6.4.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'

  mailroom:
    image: praekeltfoundation/mailroom:2.0.9
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql
      - redis
    environment:
      - MAILROOM_DOMAIN=mailroom
      - MAILROOM_AUTH_TOKEN=Gqcqvi2PGkoZMpQi
      - MAILROOM_ATTACHMENT_DOMAIN=mailroom
      - MAILROOM_DB=postgres://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - MAILROOM_REDIS=redis://redis:6379/0
      - MAILROOM_LOG_LEVEL=debug
    command: ["mailroom", "--address", "0.0.0.0"]

volumes:
  es_data:
