#
# NOTE: This docker-compose is not used for building the rapidpro docker
#       releases, it is a compose file for local development purposes.
#

version: '2'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - rapidpro
      - courier
    links:
      - rapidpro
      - courier
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:9029:80

  rapidpro:
    image: oguya/rapidpro-docker:v5.5.0
    restart: unless-stopped
    volumes:
      - ./settings.py:/rapidpro/temba/settings.py
      - ./stack/startup.sh:/startup.sh
    links:
      - redis
      - postgresql
      - mailroom
    depends_on:
      - redis
      - postgresql
      - courier
      - mailroom
      - elasticsearch
    expose:
      - '8000'
    env_file:
      - ./extra-app-env-vars.env
    environment:
      - DOMAIN_NAME=workflows.badili.co.ke
      - ALLOWED_HOSTS=workflows.badili.co.ke
      - TEMBA_HOST=workflows.badili.co.ke
      - DJANGO_DEBUG=on
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=rY6EEymtGXHWG8RDBptW7pmKM
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=on
      - MANAGEPY_MIGRATE=on
      - MAILROOM_URL=http://mailroom:8090
      - MAILROOM_AUTH_TOKEN=sc6VbyanJW0YJ4iW
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - UWSGI_WORKERS=2

  celery:
    image: oguya/rapidpro-docker:v5.5.0
    restart: unless-stopped
    depends_on:
      - rapidpro
      - mailroom
      - elasticsearch
    links:
      - redis
      - postgresql
      - mailroom
      - elasticsearch
    env_file:
      - ./extra-app-env-vars.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=rY6EEymtGXHWG8RDBptW7pmKM
      - MAILROOM_URL=http://mailroom:8090
      - MAILROOM_AUTH_TOKEN=sc6VbyanJW0YJ4iW
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    command: ["/venv/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery"]

  redis:
    image: redis:alpine
    restart: unless-stopped

  postgresql:
    image: mdillon/postgis:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rapidpro
    volumes:
      - .postgres_data/:/var/lib/postgresql:rw

  courier:
    image: oguya/courier:v5.6.0
    env_file:
      - ./extra-app-env-vars.env
    restart: unless-stopped
    depends_on:
      - postgresql
      - redis
    expose:
      - '8080'
    links:
      - redis
      - postgresql
    environment:
      - COURIER_DB=postgres://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - COURIER_REDIS=redis://redis:6379/0
      - COURIER_DOMAIN=localhost
      - COURIER_LOG_LEVEL=debug
      - COURIER_SPOOL_DIR=/home/courier/spool/persisted/

  indexer:
    image: praekeltfoundation/rp-indexer:latest
    restart: unless-stopped
    depends_on:
      - postgresql
      - elasticsearch
    links:
      - postgresql
      - elasticsearch
    environment:
      - INDEXER_DB=postgresql://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - INDEXER_ELASTIC_URL=http://elasticsearch:9200

  elasticsearch:
    image: elasticsearch:6.4.0
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'

  mailroom:
    image: oguya/mailroom:v5.5.1
    restart: unless-stopped
    env_file:
      - ./extra-app-env-vars.env
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql
      - redis
    environment:
      - MAILROOM_DOMAIN=mailroom
      - MAILROOM_AUTH_TOKEN=sc6VbyanJW0YJ4iW
      - MAILROOM_ATTACHMENT_DOMAIN=workflows.badili.co.ke
      - MAILROOM_DB=postgres://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - MAILROOM_REDIS=redis://redis:6379/0
      - MAILROOM_LOG_LEVEL=debug
    command: ["mailroom", "--address", "0.0.0.0"]

volumes:
  es_data:

